### ISSUE TITLE
[Errno 111] Connection refused on docker container

### ISSUE THREAD

**Issue by iripatx** [ros-drivers/nmea_navsat_driver#146]
Hi, I am trying to test this node on a docker container based on `ros:noetic-perception` with GPSD installed and working.

I have a GPS receiver that publishes info on serial port `/dev/ttyACM0`. However, when I try to run the node using:

`rosrun nmea_navsat_driver nmea_serial_driver _port:=/dev/ttyACM0 _baud:=4800`

I get the following output:

> Traceback (most recent call last):
  File "/opt/ros/noetic/lib/nmea_navsat_driver/nmea_serial_driver", line 38, in <module>
    libnmea_navsat_driver.nodes.nmea_serial_driver.main()
  File "/opt/ros/noetic/lib/python3/dist-packages/libnmea_navsat_driver/nodes/nmea_serial_driver.py", line 54, in main
    rospy.init_node('nmea_serial_driver')
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 326, in init_node
    _init_node_params(argv, name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 186, in _init_node_params
    set_param(rosgraph.names.PRIV_NAME + param_name, param_value)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 539, in set_param
    _param_server[param_name] = param_value #MasterProxy does all the magic for us
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 136, in __setitem__
    self.target.setParam(rospy.names.get_caller_id(), resolved_key, val)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

I verified that my device is outputting info using `cat /dev/ttyACM0` and `gpsmon /dev/ttyACM0`. I'm also able to start GPSD on the container and view the info with `cgps`. GPSD isn't complaining about creating a socket, so I don't know if I'm missing something.

Additional info:

- `docker run` command: `docker run -it --rm --name ros-gps --network host --device=/dev/ttyACM0 $tag`

Thank you.

**Comment by evenator** [comment]
Only one process can connect to a serial port at a time, and you're attempting to connect to your GPS device with both this driver and gpsd. If you're using gpsd, you probably should look at the [gpsd_client](http://wiki.ros.org/gpsd_client) to connect your GPS to ROS.
