### ISSUE TITLE
Fix missing runtime dependency

### ISSUE THREAD

**Issue by evenator** [ros-drivers/nmea_navsat_driver#62]
When building the package and running the driver with minimal dependencies installed, the following Python error appears because the dependency on `tf` is not declared in `package.xml`:
```
Traceback (most recent call last):
  File "/home/ed/code/nmea_navsat_driver_ws/install/lib/nmea_navsat_driver/nmea_serial_driver", line 39, in <module>
    import libnmea_navsat_driver.driver
  File "/home/ed/code/nmea_navsat_driver_ws/install/lib/python2.7/dist-packages/libnmea_navsat_driver/driver.py", line 39, in <module>
    from tf.transformations import quaternion_from_euler
ImportError: No module named tf.transformations
```

**Comment by anubhav1772** [comment]
Try installing the module using` sudo apt-get install ros-<ros-distro>-tf-transformations`.

**Comment by evenator** [comment]
That's a good workaround until we can fix the package dependencies so it's installed automatically.
