### ISSUE TITLE
In ROS2, nmea_topic_driver Fails to Subscribe

### ISSUE THREAD

**Issue by evenator** [ros-drivers/nmea_navsat_driver#71]
```
Traceback (most recent call last):
  File "install/nmea_navsat_driver/lib/nmea_navsat_driver/nmea_topic_driver", line 11, in <module>
    load_entry_point('libnmea-navsat-driver==0.5.1', 'console_scripts', 'nmea_topic_driver')()
  File "/workspace/install/nmea_navsat_driver/lib/python3.6/site-packages/scripts/nmea_topic_driver.py", line 60, in main
    Sentence, 'nmea_sentence', nmea_sentence_callback, driver)
TypeError: create_subscription() takes 4 positional arguments but 5 were given
```

**Comment by klintan** [comment]
This could probably be closed, since the fix is already implemented :)
